package com.lateralthoughts.points.repositories

import com.lateralthoughts.points.model.records.RewardingActionCategory

trait RewardingActionCategoryRepository extends Repository[RewardingActionCategory]

object RewardingActionCategoryRepository extends RewardingActionCategoryRepository
