package com.lateralthoughts.points.repositories

import com.lateralthoughts.points.model.records.RewardingActionCategory

object RewardingActionCategoryRepository extends Repository[RewardingActionCategory]
